# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'zirnevisQT.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(751, 330)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.movieName = QtWidgets.QLineEdit(self.centralwidget)
        self.movieName.setGeometry(QtCore.QRect(120, 10, 191, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.movieName.sizePolicy().hasHeightForWidth())
        self.movieName.setSizePolicy(sizePolicy)
        self.movieName.setObjectName("movieName")
        self.downloadPath = QtWidgets.QLineEdit(self.centralwidget)
        self.downloadPath.setGeometry(QtCore.QRect(120, 50, 191, 25))
        self.downloadPath.setObjectName("downloadPath")
        self.btnStart = QtWidgets.QPushButton(self.centralwidget)
        self.btnStart.setGeometry(QtCore.QRect(280, 110, 111, 25))
        self.btnStart.setObjectName("btnStart")
        self.downloadPathButton = QtWidgets.QPushButton(self.centralwidget)
        self.downloadPathButton.setGeometry(QtCore.QRect(320, 50, 83, 25))
        self.downloadPathButton.setObjectName("downloadPathButton")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 90, 251, 101))
        self.groupBox.setObjectName("groupBox")
        self.rdbBRRip = QtWidgets.QRadioButton(self.groupBox)
        self.rdbBRRip.setGeometry(QtCore.QRect(90, 70, 71, 23))
        self.rdbBRRip.setObjectName("rdbBRRip")
        self.rdbHDTV = QtWidgets.QRadioButton(self.groupBox)
        self.rdbHDTV.setGeometry(QtCore.QRect(170, 70, 61, 23))
        self.rdbHDTV.setObjectName("rdbHDTV")
        self.rdbWebRip = QtWidgets.QRadioButton(self.groupBox)
        self.rdbWebRip.setGeometry(QtCore.QRect(170, 30, 71, 23))
        self.rdbWebRip.setObjectName("rdbWebRip")
        self.rdbDVDRip = QtWidgets.QRadioButton(self.groupBox)
        self.rdbDVDRip.setGeometry(QtCore.QRect(10, 70, 81, 23))
        self.rdbDVDRip.setObjectName("rdbDVDRip")
        self.rdbBlueRay = QtWidgets.QRadioButton(self.groupBox)
        self.rdbBlueRay.setGeometry(QtCore.QRect(10, 30, 71, 23))
        self.rdbBlueRay.setObjectName("rdbBlueRay")
        self.rdbWebDL = QtWidgets.QRadioButton(self.groupBox)
        self.rdbWebDL.setGeometry(QtCore.QRect(90, 30, 71, 23))
        self.rdbWebDL.setObjectName("rdbWebDL")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 200, 211, 61))
        self.groupBox_2.setObjectName("groupBox_2")
        self.res1080 = QtWidgets.QRadioButton(self.groupBox_2)
        self.res1080.setGeometry(QtCore.QRect(130, 30, 61, 23))
        self.res1080.setObjectName("res1080")
        self.res480 = QtWidgets.QRadioButton(self.groupBox_2)
        self.res480.setGeometry(QtCore.QRect(10, 30, 51, 23))
        self.res480.setObjectName("res480")
        self.res720 = QtWidgets.QRadioButton(self.groupBox_2)
        self.res720.setGeometry(QtCore.QRect(70, 30, 51, 23))
        self.res720.setObjectName("res720")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 81, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 101, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(690, 270, 51, 20))
        self.label_3.setObjectName("label_3")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(410, 10, 331, 251))
        self.groupBox_3.setObjectName("groupBox_3")
        self.txtlogs = QtWidgets.QTextBrowser(self.groupBox_3)
        self.txtlogs.setGeometry(QtCore.QRect(0, 20, 331, 231))
        self.txtlogs.setObjectName("txtlogs")
        self.detailsBtn = QtWidgets.QPushButton(self.centralwidget)
        self.detailsBtn.setGeometry(QtCore.QRect(280, 140, 111, 25))
        self.detailsBtn.setObjectName("detailsBtn")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 270, 271, 21))
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 751, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.downloadPathButton.clicked.connect(MainWindow.deleteLater)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.downloadPath.setText(_translate("MainWindow", "/home/Desktop"))
        self.btnStart.setText(_translate("MainWindow", "Start"))
        self.downloadPathButton.setText(_translate("MainWindow", "Change"))
        self.groupBox.setTitle(_translate("MainWindow", "Quality"))
        self.rdbBRRip.setText(_translate("MainWindow", "BRRip"))
        self.rdbHDTV.setText(_translate("MainWindow", "HDTV"))
        self.rdbWebRip.setText(_translate("MainWindow", "WebRip"))
        self.rdbDVDRip.setText(_translate("MainWindow", "DVDRip"))
        self.rdbBlueRay.setText(_translate("MainWindow", "BluRay"))
        self.rdbWebDL.setText(_translate("MainWindow", "Web-Dl"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Resolution"))
        self.res1080.setText(_translate("MainWindow", "1080"))
        self.res480.setText(_translate("MainWindow", "480"))
        self.res720.setText(_translate("MainWindow", "720"))
        self.label.setText(_translate("MainWindow", "Movie Name"))
        self.label_2.setText(_translate("MainWindow", "Download Path"))
        self.label_3.setText(_translate("MainWindow", "v 1.0.0"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Logs"))
        self.detailsBtn.setText(_translate("MainWindow", "Details"))
        self.label_4.setText(_translate("MainWindow", "Free Subtitle Downloader (Persian/Farsi)"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
